version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: pip
    directory: /subdir
    schedule:
      interval: monthly
    pull-request-branch-name:
      separator: "-"
